#Adding comment
name: Create S3 Static Website
on:
  push:
    branches:
      - main
jobs:
  create-s3-static-website:
    runs-on: ubuntu-latest
    steps:
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Configure Terraform
        run: terraform init
      - name: Create S3 Bucket
        run: terraform apply /home/runner/work/Srivathsan_Legendary_Resume/

        
