name: Create S3 bucket static website

on:
  push:
    branches:
      - main  # To the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
        run: |
          aws --version
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

      - name: Run AWS CLI Command
        run: |
          # Example: List S3 buckets
          aws s3 ls

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        working-directory: ./Terraform  # Specify the path to your Terraform folder
        run: terraform init

      - name: Apply Terraform
        working-directory: ./Terraform  # Specify the path to your Terraform folder
        run: terraform apply -auto-approve
