name: Create S3 Static Website
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/terraform@v1.2.3
        with:
          working-directory: Terraform
          args: init
      - uses: hashicorp/terraform@v1.2.3
        with:
          working-directory: Terraform
          args: apply
