name: Upload Website

on:
  push:
    branches:
      - main  # To the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/checkout@master
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  

      - name: Debug AWS CLI Configuration
        run: |
          echo "AWS Access Key ID: $AWS_ACCESS_KEY_ID"
          echo "AWS Secret Access Key: $AWS_SECRET_ACCESS_KEY"
          aws configure list

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        working-directory: ./Terraform  # Specify the path to your Terraform folder
        run: terraform init

      - name: Apply Terraform
        working-directory: ./Terraform  # Specify the path to your Terraform folder
        run: terraform apply -auto-approve
