name: Terraform Deployment

on:
  push:
    branches:
      - main  # To the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        working-directory: ./Terraform  # Specify the path to your Terraform folder
        run: terraform init

      - name: Apply Terraform
        working-directory: ./Terraform  # Specify the path to your Terraform folder
        run: terraform apply -auto-approve
